function sfg2TestSummary(d){return Milestones.sfg2Skills(d).map(s=>'<li>'+s.name+' · '+s.reps+(s.each?' / side':s.oneSide?' on one side':' reps')+' · '+(s.double?'2 × ':'')+s.weight+' kg</li>').join('');}
function sfg2ResultSummary(a){
 const f=a.result||{};
 return Milestones.sfg2Skills(a.goal).map(s=>'<li>'+s.name+': '+msEscape(f[s.id+'Weight']??'—')+' kg'+(s.double?' / bell':'')+' · '+msEscape(f[s.id+'Reps']??'—')+(s.each?' / '+msEscape(f[s.id+'Right']??'—')+' reps (L / R)':' reps')+(s.oneSide?' · '+msEscape(f.bentSide||''):'')+'</li>').join('')+'<li>Clean &amp; strict press: '+msEscape(f.pressWeight??'—')+' kg · '+msEscape(f.pressReps??'—')+' rep · '+msEscape(f.pressSide||'')+(f.pressEvidence?' · saved press from '+new Date(f.pressEvidence.finishedAt).toLocaleDateString('en-GB'):'')+'</li>';
}
function renderSfg2Detail(r){
 const d=r.goal,history=state.milestones.attempts.filter(a=>a.goal.id==='sfg2').slice().reverse();
 document.getElementById('milestonesPanel').innerHTML='<button class="ghost" data-ms-back>← All milestones</button><article class="panel ms-detail"><img class="ms-art" src="badge-sfg2.png" alt="SFG II badge"><h2>SFG II</h2><p class="small-copy">Personal training milestone. Demonstrate all five skills and a qualifying clean &amp; strict press. Practice sessions never award this badge.</p><ul class="ms-checks">'+sfg2TestSummary(d)+'<li>Clean &amp; strict press · 1 rep on either arm · '+d.pressWeight+' kg</li></ul><p class="small-copy">Test weights follow the StrongFirst SFG II tables for your current category, age and bodyweight. They are separate from the lighter practice weights and your optional personal press goal.</p><ul class="ms-checks">'+r.checks.map(c=>'<li>'+(c.done?'✓ ':'○ ')+msEscape(c.label)+'</li>').join('')+'</ul><button class="primary" id="msStart" '+(!r.available?'disabled':'')+'>Start performance check</button><p class="small-copy">Record actual reps and weights. Your Six rotation stays in place.</p><details><summary>About the standard</summary><p class="small-copy">Personal, self-reported milestone, not StrongFirst certification. Skills and press table: strongfirst.com/certifications/sfg-ii-requirements/ (8 October 2026). Press categories use bodyweight converted to pounds, with the published upper boundaries and separate masters requirements from age 50. Double snatch uses one standard 4 kg size below the snatch-test bell.</p><p class="small-copy">Clean the press bell; pause in the rack, keep feet planted and knees locked, then press without a dip or downward movement. Finish with a motionless overhead lockout. Either arm is sufficient.</p></details></article>'+(history.length?'<details class="panel" open><summary>Attempt history</summary>'+history.map(a=>'<div class="ms-history"><strong>'+new Date(a.finishedAt).toLocaleDateString('en-GB')+' · '+a.outcome+'</strong><p class="small-copy">'+a.goal.profile.sex+' · age '+a.goal.profile.age+' · '+a.goal.profile.bodyweight+' kg bodyweight · press target '+a.goal.pressWeight+' kg</p><ul class="ms-checks">'+sfg2ResultSummary(a)+'</ul></div>').join('')+'</details>':'');
}
function sfg2WeightField(name,label,value,max=500){return '<label>'+label+'<input name="'+name+'" type="number" min="0" max="'+max+'" step="0.1" required value="'+msEscape(value??'')+'"></label>';}
function sfg2Side(name,value){return '<label>Arm<select name="'+name+'"><option value="Left" '+(value!=='Right'?'selected':'')+'>Left</option><option value="Right" '+(value==='Right'?'selected':'')+'>Right</option></select></label>';}
function renderSfg2Attempt(){
 const a=state.milestones.active,d=a.goal,f=a.form||{},saved=Milestones.sfg2SavedPress(state.milestones,d);
 document.getElementById('milestonesPanel').innerHTML='<article class="panel ms-attempt"><p class="eyebrow">Separate performance check</p><h2>SFG II</h2><p class="small-copy">Record what you demonstrate today. Rest as needed. An incomplete check can also be saved.</p><form id="msResultForm">'+Milestones.sfg2Skills(d).map(s=>'<fieldset class="sfg2-result"><legend>'+s.name+'</legend><p class="small-copy">Target: '+s.reps+(s.each?' / side':s.oneSide?' on either side':' reps')+' · '+(s.double?'2 × ':'')+s.weight+' kg</p><div class="ms-fields">'+sfg2WeightField(s.id+'Weight',s.double?'Actual kg / bell':'Actual kg',f[s.id+'Weight'])+msInput(s.id+'Reps',s.each?'Reps · left':'Reps',100,f[s.id+'Reps'])+(s.each?msInput(s.id+'Right','Reps · right',100,f[s.id+'Right']):s.oneSide?sfg2Side('bentSide',f.bentSide):'')+'</div></fieldset>').join('')+'<fieldset class="sfg2-result"><legend>Clean &amp; strict press</legend><p class="small-copy">Target: 1 rep · '+d.pressWeight+' kg · either arm</p>'+(saved?'<label class="ms-confirm"><input type="checkbox" name="useSavedPress" '+(f.useSavedPress?'checked':'')+'>Use saved '+saved.result.weight+' kg press · '+new Date(saved.finishedAt).toLocaleDateString('en-GB')+'</label>':'')+'<div class="ms-fields" id="sfg2PressFields">'+sfg2WeightField('pressWeight','Actual kg',f.pressWeight,200)+msInput('pressReps','Reps',10,f.pressReps)+sfg2Side('pressSide',f.pressSide)+'</div></fieldset><label class="ms-confirm"><input type="checkbox" name="controlled" '+(f.controlled?'checked':'')+'>All counted repetitions were technically controlled, with full range and lockouts. Double lifts used two bells of the recorded weight.</label><button class="primary" type="submit">Save performance check</button></form><button class="ghost" id="msAbort">End without a result</button></article>';
 syncSfg2PressFields();
}
function syncSfg2PressFields(){
 const field=document.getElementById('sfg2PressFields');if(!field)return;
 const use=document.querySelector('[name="useSavedPress"]')?.checked===true;
 field.hidden=use;field.querySelectorAll('input,select').forEach(x=>{x.disabled=use;});
}
